site_name: TechComm Art
theme: 
 name: material
 features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    - navigation.path
 language: en
 palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: lime
markdown_extensions:
  #Admonitions or call-outs
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  #Attribute lists ana buttons
  - attr_list

  #Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  #Table
  - tables

  #Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  #Grid
  - attr_list
  - md_in_html

  #Images
  - attr_list
  - md_in_html

  #Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  
  #Tooltips
  - abbr
  - attr_list
  - pymdownx.snippets

copyright: |
  &copy; 2023 <a href="https://github.com/tannisanta"target="_blank"rel="noopener">Tania Tsakun</a>