site_name: TechComm Art
language: en
site_author: Tetiana Tsakun
site_description: >-
  MkDocs website for practicing and sharing TechComm materials.

theme: 
 name: material
 features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
 
 nav:
    - Home: index.md
    - Books:
        - TechComm books: Books.md
        - Create website: MkDocs Website.md
    - Blogs: 
        - TechComm blogs: Techcomm_blogs.md
        - Create website: MkDocs Website.md
    - Mkdocs website:
        - Create website: MkDocs Website.md
        - TechComm books: Books.md

 palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: lime
markdown_extensions:
  #Admonitions or call-outs
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  #Attribute lists ana buttons
  - attr_list

  #Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  #Table
  - tables

  #Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  #Grid
  - attr_list
  - md_in_html

  #Images
  - attr_list
  - md_in_html

  #Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  
  #Tooltips
  - abbr
  - attr_list
  - pymdownx.snippets

  #TOC
  - toc:
      baselevel: 2

copyright: |
  &copy; 2023 <a href="https://github.com/tannisanta"target="_blank"rel="noopener">Tania Tsakun</a>